// playgrounds/react/src/App.tsx
import { useCallback, useState } from "react";

const App = () => {
  const [count, setCount] = useState(0);

  const add = useCallback(() => {
    setCount((prevCount) => prevCount + 1);
  }, []);

  return (
    <div>
      <img src="/logo.svg" alt="React logo" style={{ width: "100px" }} />
      <h1>Hello, Web App!</h1>
      <button onClick={add}>Add</button>
      <p>Count: {count}</p>
    </div>
  );
};

export default App;

// playgrounds/vue/src/App.vue
<template>
  <div>
    <img src="/logo.svg" alt="Vue logo" />
    <h1>Hello, Web App!</h1>
    <button @click="add">Add</button>
    <p>Count: {{ count }}</p>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";
const count = ref(0);
const add = () => {
  count.value++;
};
</script>

<style scoped>
img {
  width: 100px;
}
</style>
